services:
  - type: web
    name: poseperfect-backend
    runtime: python
    repo: https://github.com/lxkka21/PosePerfect
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn flask_app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
